In [ ]:
import numpy as np

# Example Without Unviversal Functions , here we will use Python in built zip()

In [ ]:
x = [1,2,3,4]
y = [4,5,6,7]
z = []
for i, j in zip(x,y):
  z.append(i+j)
print(z)

[5, 7, 9, 11]


# Binary Universal Functions of Numpy

In [ ]:
x = np.arange(4,40)
y = np.arange(2.6,30.5)
print(x)
print(y)


[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39]
[ 2.6  3.6  4.6  5.6  6.6  7.6  8.6  9.6 10.6 11.6 12.6 13.6 14.6 15.6
 16.6 17.6 18.6 19.6 20.6 21.6 22.6 23.6 24.6 25.6 26.6 27.6 28.6 29.6]


# add coresponding elements in arrays

 # With Unviversal Functions , we will now use add() function 

In [ ]:
x = [1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)

[ 5  7  9 11]


# Numpy Universal Function


In [ ]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


# Square roues of each element

In [ ]:
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


# Absolute Value

In [ ]:
print(np.absolute(np1))

[0 1 2 3 4 5 6 7 8 9]


# Exponents

In [ ]:
print(np.max(np1))
print(np.min(np1))

9
0


# Sign Positive or negative

In [ ]:
print(np.sign(np1))

[0 1 1 1 1 1 1 1 1 1]


#Trig Sin Cos Log

In [ ]:
print(np.log(np1))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-10-08c2794a484a>:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))


#Unary Universal Functions of Numpy

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Compute square root

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

#compute exponential value

In [ ]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

# Natural logarithm base e,log10,log2 and log1p

In [ ]:
np.log(a)
print(a)
np.log10(a)
print(a)
np.log2(a)
print(a)
np.log1p(a)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


#compute the sign of each element(1=+ve,0=-ve,-1=-ve)


In [ ]:
np.sign(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#new array

In [ ]:
a1 = np.arange(0.2,20.1)
print(a1)

[ 0.2  1.2  2.2  3.2  4.2  5.2  6.2  7.2  8.2  9.2 10.2 11.2 12.2 13.2
 14.2 15.2 16.2 17.2 18.2 19.2]


#compute exponential value

In [ ]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

# Compute the ceiling of each element(i.e. the smaller integer is greater or equal to that number) 


In [ ]:
np.ceil(a1)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

# Compute the floor of each element(i.e. the largest integer is less or equal to that number) 


In [ ]:
np.floor(a1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

# Round elements to the nearest interger 

# Round elements to the nearest interger 

In [ ]:
np.rint(a1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

# Return fractional or integer parts as a separate array


In [ ]:
np.modf(a1)

(array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
        0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.]))

# Return boolean array indicating weather each value is NaN (Not a Number)

In [ ]:
np.isnan(a1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

# Return boolean array indicating weather each element is finite

In [ ]:
np.isfinite(a1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

# Return boolean array indicating weather each element is infinite

In [ ]:
np.isinf(a1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])